title: phuhoang
timezone: UTC
email: phuhoang@sina.com
author: phuhoang
description: phuhoang 个人博客
baseurl: ''
url: pxyi.github.io
github_username: pxyi
theme: minima

valine: true


plugins: [jekyll-paginate]

paginate: 10  
paginate_path: ":num"
